"""empty message

Revision ID: 045e4248cd89
Revises: ec783c373312
Create Date: 2021-11-27 13:45:13.436844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045e4248cd89'
down_revision = 'ec783c373312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('login')
    op.alter_column('place', 'latitude',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('place', 'longitude',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('lastTime', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'lastTime')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.alter_column('place', 'longitude',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('place', 'latitude',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('login',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('lastTime', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], name='login_idUser_fkey'),
    sa.PrimaryKeyConstraint('id', name='login_pkey'),
    sa.UniqueConstraint('email', name='login_email_key')
    )
    op.drop_table('customer')
    # ### end Alembic commands ###
