"""empty message

Revision ID: 272b7e800699
Revises: 045e4248cd89
Create Date: 2021-11-30 18:11:26.957643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272b7e800699'
down_revision = '045e4248cd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_film')
    op.add_column('film', sa.Column('urlPhoto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'urlPhoto')
    op.create_table('photo_film',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idFilm', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('urlPhoto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idFilm'], ['film.id'], name='photo_film_idFilm_fkey'),
    sa.PrimaryKeyConstraint('id', name='photo_film_pkey')
    )
    # ### end Alembic commands ###
